title: Steam ban notifier
author: Catalysm
email: niekcandaele@gmail.com
description: A discord bot that lets you know when someone gets banned
twitter_username: none
github_username:  niekcandaele

sass:
    style: compressed