title: Steam ban notifier
author: Catalysm
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll

twitter_username: macrod68
github_username:  niekcandaele

sass:
    style: compressed